package:
  name: htcondor-python
  version: {{ environ.get('CONDOR_VERSION','') }}
source:
  git_url: https://github.com/htcondor/htcondor
  git_tag: V{{ environ.get('CONDOR_VERSION','').replace('.', '_') }}
build:
  number: 1
  rpaths:
    - lib/
    - lib64/
requirements:
  build:
    - python #{{ environ.get('PY_VER') }}
    - autoconf
    - automake
    - cmake
    - openssl
    - curl
    - pcre
    - libxml2
    - krb5
    - uuid
    - boost
  run:
    - python #{{ environ.get('PY_VER') }}
    - boost

test:
  imports:
    - htcondor
    - classad

about:
  home: https://research.cs.wisc.edu/htcondor/
  license: Apache v2.0
